org: mateomansilla
app: crud-http
service: crud-http
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:559668413333:table/TaskTable
        
        

functions:
  hello:
    handler: src/handler.hello
    events:
      - httpApi:
          path: /
          method: get

  createPoint:
    handler: src/addPoints.addPoints
    events:
      - httpApi:
          path: /points
          method: post
  
  getPoints:
    handler: src/getPoints.getPoints
    events:
      - httpApi:
          path: /points
          method: get

  getPoint:
    handler: src/getPoint.getPoint
    events:
      - httpApi:
          path: /points/{id}
          method: get

  updatePoint:
    handler: src/updatePoint.updatePoint
    events:
      - httpApi:
          path: /points/{id}
          method: put

  deletePoint:
    handler: src/deletePoint.deletePoint
    events:
      - httpApi:
        path: /points/{id}
        method: delete



resources:
  Resources:
    TaskTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: TaskTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
            - AttributeName: id
              KeyType: HASH
    
    
     
    





